# Note: This is intended for use in local development
version: '3.3'
services:
  reactql-dev:
    build: .
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - 4006:4006
      - 4006:4006
    environment:
      HOST: "0.0.0.0"
      BROWSER_HOST: "0.0.0.0"
      PORT: "4006"
    command: npm start
